@ alan yeh. ai by hand
https://aibyhand.substack.com/

In [1]:
!python3 --version

Python 3.11.7


In [62]:
import numpy as np
np.version.full_version

'1.26.4'

In [33]:
def m(*x):
    return np.array([[*x]])

def M(*x):
    return np.array([*x])

m(5,2).T!=m(5,2)

array([[False,  True],
       [ True, False]])

https://aibyhand.substack.com/p/w2-matrix-multiplication

In [34]:
# ex1
m(3)@m(5,2)

array([[15,  6]])

In [35]:
# ex2
m(3,2).T@m(4)

array([[12],
       [ 8]])

In [36]:
# ex3
m(1,-1).T@m(1,-1)

array([[ 1, -1],
       [-1,  1]])

In [37]:
# ex4
m(3,2).T@m(2,-2)

array([[ 6, -6],
       [ 4, -4]])

In [38]:
# ex5
m(1,0).T@m(3,-5)

array([[ 3, -5],
       [ 0,  0]])

In [39]:
# ex6
m(1,-1).T@m(4,-2)

array([[ 4, -2],
       [-4,  2]])

In [40]:
# ex7
M([1,1],[1,-1])@M([1,3],[3,2])

array([[ 4,  5],
       [-2,  1]])

In [41]:
# ex8
M([1,1],[1,-1])@M([2,5],[4,3])

array([[ 6,  8],
       [-2,  2]])

In [42]:
# ex9
M([3,2],[4,5])@M([1,1],[-1,1])

array([[ 1,  5],
       [-1,  9]])

In [43]:
# ex10
M([5,5],[-2,2])@M([1,1],[-1,1])

array([[ 0, 10],
       [-4,  0]])

In [44]:
# ex11
M([3,1],[2,4])@M([1,1,-1,-1],[-1,1,1,-1])

array([[ 2,  4, -2, -4],
       [-2,  6,  2, -6]])

In [45]:
# ex12
M([1,1],[1,-1],[1,0])@M([4,3,2,1],[1,2,1,2])

array([[ 5,  5,  3,  3],
       [ 3,  1,  1, -1],
       [ 4,  3,  2,  1]])

In [46]:
# ex13
M([1,0,1],[0,1,1])@M([2,1],[3,5],[4,-1])

array([[6, 0],
       [7, 4]])

In [50]:
# ex14
M([3,3,-1],[2,1,3])@M([1,1],[1,0],[0,1])

array([[6, 2],
       [3, 5]])

In [51]:
# ex15
M([1,1],[1,0],[0,1])@M([3,3,-1],[2,1,3])

array([[ 5,  4,  2],
       [ 3,  3, -1],
       [ 2,  1,  3]])

In [52]:
# ex16
M([0,1,1],[1,1,0])@M([3,2],[2,1],[1,-2])

array([[ 3, -1],
       [ 5,  3]])

In [53]:
# ex17
M([1,0,1],[1,1,0])@M([-2,2],[4,4],[3,1])

array([[1, 3],
       [2, 6]])

In [54]:
# ex18
M([1,1,0,1],[1,0,1,-1])@M([3,2],[2,0],[1,2],[4,3])

array([[9, 5],
       [0, 1]])

In [55]:
# ex19
M([3,2],[2,0],[1,2],[4,3])@M([1,1,0,1],[1,0,1,-1])

array([[ 5,  3,  2,  1],
       [ 2,  2,  0,  2],
       [ 3,  1,  2, -1],
       [ 7,  4,  3,  1]])

In [56]:
# ex20
M([1,1,0,0],[0,1,1,0],[0,0,1,1],[1,0,0,1])@M([3,2],[2,1],[1,1],[4,3])

array([[5, 3],
       [3, 2],
       [5, 4],
       [7, 5]])

In [57]:
# ex21
M([1,-1,0,0],[0,1,-1,0],[0,0,1,-1],[-1,0,0,1])@M([3,2],[2,1],[1,1],[4,3])

array([[ 1,  1],
       [ 1,  0],
       [-3, -2],
       [ 1,  1]])

In [63]:
# ex22
M([9,-2,0,5],[13,3,1,4])@M([1,0,0,0,1],[0,1,0,0,1],[0,0,1,0,0],[0,0,0,1,0])

array([[ 9, -2,  0,  5,  7],
       [13,  3,  1,  4, 16]])

In [65]:
# ex23
M([2,-1,1,0],[3,2,4,1])@M([0,0,0,1,1],[1,0,1,0,1],[0,1,1,0,1],[0,1,0,1,0])

array([[-1,  1,  0,  2,  2],
       [ 2,  5,  6,  4,  9]])

In [67]:
# ex24
M([-1,1,0,0],[0,1,0,0],[-1,0,1,0],[1,0,0,1])@M([3,2],[2,1],[1,1],[4,3])

array([[-1, -1],
       [ 2,  1],
       [-2, -1],
       [ 7,  5]])

In [48]:
# ex25
M([1,1,1,0],[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,-1,1])@M([0,0,0,1,1],[1,0,1,0,1],[0,1,1,0,1],[0,0,0,1,0])

array([[ 1,  1,  2,  1,  3],
       [ 1,  1,  2,  1,  2],
       [ 0,  1,  1,  2,  2],
       [ 1,  0,  1,  2,  2],
       [ 1, -1,  0,  2,  1]])

https://aibyhand.substack.com/p/w3-linear-layer

In [116]:
def L(w,x):
    # bias w[:,-1:]
    # weight w[:,:-1]
    return w[:,:-1]@x+w[:,-1:]

In [117]:
L(M([3,0]), m(4))

array([[12]])

In [118]:
L(M([3,2]), m(4))

array([[14]])

In [119]:
L(M([3,-1]), m(4))

array([[11]])

In [120]:
L(M([3,2],[3,-2]), m(4))

array([[14],
       [10]])

In [121]:
L(M([3,2],[3,-2],[3,-4]), m(2))

array([[8],
       [4],
       [2]])

In [122]:
L(M([1,-1,0]), M([2],[1]))

array([[1]])

In [123]:
L(M([2,1,2]), M([2],[3]))

array([[9]])

In [124]:
L(M([1,1,0],[1,-1,0]), M([2],[-1]))

array([[1],
       [3]])

In [125]:
L(M([1,1,2],[1,-1,2]), M([2],[1]))

array([[5],
       [3]])

In [126]:
L(M([1,1,0],[0,1,0],[1,-1,0]), M([3],[2]))

array([[5],
       [2],
       [1]])

In [127]:
L(M([1,1,0],[1,-1,0],[-1,1,0]), M([4],[7]))

array([[11],
       [-3],
       [ 3]])

In [128]:
L(M([1,-1,1,0],[1,1,1,0]), M([1],[-2],[3]))

array([[6],
       [2]])

In [129]:
L(M([1,1,0,-1],[1,0,1,-1]), M([3],[1],[2]))

array([[3],
       [4]])

In [130]:
L(M([1,1,0,0],[0,1,1,0],[1,0,1,0]), M([3],[1],[2]))

array([[4],
       [3],
       [5]])

In [131]:
L(M([1,1,0]), M([2],[3]))

array([[5]])

In [132]:
L(M([1,0,0]), M([2],[3]))

array([[2]])

In [133]:
L(M([1,1,2]), M([2],[1]))

array([[5]])

In [134]:
L(M([1,1,-2]), M([2],[1]))

array([[1]])

In [135]:
L(M([-1,1,0],[1,-1,0]), M([3],[5]))

array([[ 2],
       [-2]])

In [136]:
L(M([1,2,0],[1,3,0]), M([4],[2]))

array([[ 8],
       [10]])

In [137]:
L(M([1,2,1],[1,2,5]), M([3],[2]))

array([[ 8],
       [12]])

In [138]:
L(M([1,1,0],[2,1,0],[3,0,0]), M([3],[2]))

array([[5],
       [8],
       [9]])

In [139]:
L(M([1,1,0],[2,1,0],[3,1,0]), M([2],[1]))

array([[3],
       [5],
       [7]])

In [141]:
L(M([1,1,0,0],[1,1,-1,0],[1,1,1,0]), M([2],[1],[2]))

array([[3],
       [1],
       [5]])

In [146]:
L(M([1,1,0,0],[1,1,0,-2],[1,1,0,-4]), M([2],[5],[1]))

array([[7],
       [5],
       [3]])

https://aibyhand.substack.com/p/w4-activation

In [328]:
def relu(x):
    return np.where(x >= 0, x, x==0)

def sig3(x):
    cond1 = x >= 2
    cond2 = (-1 <= x) & (x <= 1)
    cond3 = (x <= -2)
    vals = [1, 0.5, 0]
    return np.select([cond1, cond2, cond3], vals)

def sig5(x):
    cond1 = x >= 2
    cond2 = (1 <= x) & (x < 2)
    cond3 = (0 <= x) & (x < 1)
    cond4 = (-2 < x) & (x < 0)
    cond5 = (x <= -2)
    vals = [1, 0.7, 0.5, 0.3, 0]
    return np.select([cond1, cond2, cond3, cond4, cond5], vals)

def tanh3(x):
    cond1 = x >= 2
    cond2 = (-1 <= x) & (x <= 1)
    cond3 = (x <= -2)
    vals = [1, 0, -1]
    return np.select([cond1, cond2, cond3], vals)

def tanh5(x):
    cond1 = x >= 2
    cond2 = (1 <= x) & (x < 2)
    cond3 = (0 <= x) & (x < 1)
    cond4 = (-2 < x) & (x < 0)
    cond5 = (x <= -2)
    vals = [1, 0.8, 0, -0.8, -1]
    return np.select([cond1, cond2, cond3, cond4, cond5], vals)

In [184]:
x = L(M([1,-1,0],[1,-2,0],[1,-3,0]), M([3],[2]))
relu(x)

[[ 1]
 [-1]
 [-3]]


array([[1],
       [0],
       [0]])

In [185]:
x = L(M([1,1,-2],[1,1,-4],[1,1,-6]), M([3],[2]))
relu(x)

array([[3],
       [1],
       [0]])

In [182]:
relu(M([5],[4],[3],[2],[1],[0],[-1],[-2],[-3],[-4],[-5]))

array([[5],
       [4],
       [3],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [199]:
relu(M([[i] for i in range(5, -6, -1)]))[0]

array([[5],
       [4],
       [3],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [200]:
relu(M([2],[0],[-2]))

array([[2],
       [0],
       [0]])

In [294]:
x=M([2],[0],[-2])
sig3(x)

array([[1. ],
       [0.5],
       [0. ]])

In [295]:
x=M([-3],[1],[-1])
sig3(x)

array([[0. ],
       [0.5],
       [0.5]])

In [297]:
x=M([-9],[-5],[-4])
sig3(x)

array([[0.],
       [0.],
       [0.]])

In [298]:
x=M([11],[7],[4])
sig3(x)

array([[1.],
       [1.],
       [1.]])

In [300]:
sig3(L(M([1,-1,0],[1,-2,0],[1,-3,0]), M([3],[2])))

array([[0.5],
       [0.5],
       [0. ]])

In [301]:
sig3(L(M([1,-1,3],[1,-2,3],[1,-3,3]), M([3],[2])))

array([[1. ],
       [1. ],
       [0.5]])

In [302]:
sig3(L(M([1,-1,-2],[1,-2,-2],[1,-3,-2]), M([3],[2])))

array([[0.5],
       [0. ],
       [0. ]])

In [305]:
tanh3(M([2],[0],[-2]))

array([[ 1],
       [ 0],
       [-1]])

In [307]:
tanh3(M([-9],[-5],[-4]))

array([[-1],
       [-1],
       [-1]])

In [308]:
tanh3(M([11],[7],[4]))

array([[1],
       [1],
       [1]])

In [311]:
tanh3(L(M([1,-1,0],[1,-2,0],[1,-3,0]), M([3],[2])))

array([[ 0],
       [ 0],
       [-1]])

In [312]:
tanh3(L(M([1,-1,3],[1,-2,3],[1,-3,3]), M([3],[2])))

array([[1],
       [1],
       [0]])

In [313]:
tanh3(L(M([1,-1,-2],[1,-2,-2],[1,-3,-2]), M([3],[2])))

array([[ 0],
       [-1],
       [-1]])

In [316]:
sig3(tanh3(M([1],[2],[-3])))

array([[0.5],
       [0.5],
       [0.5]])

In [319]:
sig3(relu(M([1],[2],[-3])))

array([[0.5],
       [1. ],
       [0.5]])

In [322]:
sig5(M([0,1,-1]))

array([[0.5, 0.7, 0.3]])

In [327]:
sig5(L(M([1,1,-2],[1,1,-4],[1,1,-6]), M([3],[2])))

array([[1. ],
       [0.7],
       [0.3]])

In [329]:
tanh5(M([0,1,-1]))

array([[ 0. ,  0.8, -0.8]])

In [331]:
tanh5(L(M([1,1,-2],[1,1,-4],[1,1,-6]), M([3],[2])))

array([[ 1. ],
       [ 0.8],
       [-0.8]])

In [333]:
sig5(L(M([1,0,0],[0,1,0],[1,1,0],[-1,-1,0],[1,-1,0],[-1,1,0],[-1,0,0],[0,-1,0],[0,0,0]), M([3],[2])))

array([[1. ],
       [1. ],
       [1. ],
       [0. ],
       [0.7],
       [0.3],
       [0. ],
       [0. ],
       [0.5]])

In [335]:
tanh5(L(M([1,0,0],[0,1,0],[1,1,0],[-1,-1,0],[1,-1,0],[-1,1,0],[-1,0,0],[0,-1,0],[0,0,0]), M([3],[2])))

array([[ 1. ],
       [ 1. ],
       [ 1. ],
       [-1. ],
       [ 0.8],
       [-0.8],
       [-1. ],
       [-1. ],
       [ 0. ]])

In [342]:
L(M([1,1,-5]), M([3],[1]))

array([[-1]])

In [345]:
relu(L(M([1,-1,0]), M([3],[1])))

array([[2]])

In [346]:
x = L(M([2,1,1]), M([2],[-1]))
print(x)
relu(x)

[[4]]


array([[4]])

In [347]:
x = L(M([2,1,-5]), M([2],[-1]))
print(x)
relu(x)

[[-2]]


array([[0]])

In [348]:
sig3(L(M([1,-1,-1]), M([4],[2])))

array([[0.5]])

In [350]:
sig3(L(M([2,-1,0]), M([3],[4])))

array([[1.]])

In [352]:
x = L(M([1,0,1,-2]), M([2],[5],[1]))
print(x)
relu(x)

[[1]]


array([[1]])

In [354]:
x = L(M([1,-1,0,2]), M([2],[5],[1]))
print(x)
relu(x)

[[-1]]


array([[0]])

In [355]:
x = L(M([1,-1,0,2]), M([2],[5],[1]))
print(x)
sig3(x)

[[-1]]


array([[0.5]])

In [358]:
x = L(M([0,1,-1],[1,0,0],[1,0,-1]), M([4],[6]))
print(x)
relu(x)

[[5]
 [4]
 [3]]


array([[5],
       [4],
       [3]])

In [359]:
x = L(M([1,1,-2],[1,-1,-2],[0,-1,-2]), M([5],[2]))
print(x)
relu(x)

[[ 5]
 [ 1]
 [-4]]


array([[5],
       [1],
       [0]])

In [361]:
x = L(M([1,-1,0],[1,-2,0],[1,-3,0]), M([3],[2]))
print(x)
relu(x)

[[ 1]
 [-1]
 [-3]]


array([[1],
       [0],
       [0]])

In [362]:
x = L(M([1,1,1,0],[1,1,0,0],[1,0,0,0]), M([3],[1],[2]))
print(x)
relu(x)

[[6]
 [4]
 [3]]


array([[6],
       [4],
       [3]])

In [363]:
x = L(M([1,1,0,0],[1,0,-1,0],[1,-1,0,0]), M([2],[3],[4]))
print(x)
relu(x)

[[ 5]
 [-2]
 [-1]]


array([[5],
       [0],
       [0]])

In [365]:
x = L(M([0,1,0,-3],[1,0,-1,0],[1,-1,0,0]), M([5],[2],[-3]))
print(x)
relu(x)

[[-1]
 [ 8]
 [ 3]]


array([[0],
       [8],
       [3]])

In [368]:
relu(L(M([1,1,0]), M([3],[2])))

array([[5]])

In [371]:
relu(L(M([1,-1,0]), M([4],[5])))

array([[0]])

In [373]:
relu(L(M([-1,1,0]), M([3],[5])))

array([[2]])

In [374]:
relu(L(M([1,-2,0]), M([3],[2])))

array([[0]])

In [375]:
relu(L(M([1,-1,-2]), M([3],[2])))

array([[0]])

In [380]:
relu(L(M([1,1,1,0]), M([-4],[2],[3])))

array([[1]])

In [381]:
relu(L(M([1,-1,1,0]), M([2],[3],[1])))

array([[0]])

In [382]:
relu(L(M([1,1,-2,0]), M([4],[1],[3])))

array([[0]])

In [384]:
relu(L(M([1,-1,0,0],[1,0,-1,0],[1,0,0,0]), M([2],[4],[3])))

array([[0],
       [0],
       [2]])

In [385]:
sig3(L(M([1,-1,0,0],[1,0,-1,0],[1,0,0,0]), M([2],[4],[3])))

array([[0. ],
       [0.5],
       [1. ]])

https://aibyhand.substack.com/p/w6-batch

In [386]:
(2+2+2+6)/4

3.0

In [388]:
(1+1+1+1+1+1+1)/10

0.7

In [390]:
np.mean([1,1,0,1,1,1,1,1,0,1])

0.8

In [402]:
def cen0(x):
    mean = np.mean(x)
    return x-mean

In [403]:
mu = np.mean([-1,1,1,-1])
print([-1,1,1,-1]-mu)

[-1.  1.  1. -1.]


In [404]:
mu = np.mean([-2,0,-4,-2])
print([-2,0,-4,-2]-mu)

[ 0.  2. -2.  0.]


In [405]:
cen0([3,6,3,0])

array([ 0.,  3.,  0., -3.])

In [406]:
cen0([1,4,-1,0])

array([ 0.,  3., -2., -1.])

In [412]:
L(M([1,1,0,1,0,0,0,0],[1,-1,0,0,0,0,2,0],[-1,0,1,0,1,-1,0,1]), M([2],[1],[3],[1],[2],[1],[1]))

array([[4],
       [3],
       [3]])

In [417]:
L(M([1,1,0,1,0,0,0,0,0],[1,-1,0,0,0,0,2,-1,0],[-1,0,1,0,1,-1,0,0,1]), M([2],[1],[3],[1],[2],[1],[1],[1]))

array([[4],
       [2],
       [3]])

In [426]:
e = 3
e**1/30

0.1

https://aibyhand.substack.com/p/w11-softmax

In [434]:
def sm(x):
    e = 3 # 2.71828
    x = np.power(e, x)
    return x/np.sum(x)

In [445]:
sm([6,5.9])

array([0.52743772, 0.47256228])

In [448]:
# ex1
sm(L(M([1,1,-1],[1,-1,-1]), M([2],[1])))

array([[0.9],
       [0.1]])

In [449]:
# ex2
sm(L(M([1,1,0],[1,-1,0]), M([2],[1])))

array([[0.9],
       [0.1]])

In [450]:
# ex3
sm(L(M([1,1,1],[1,-1,1]), M([2],[1])))

array([[0.9],
       [0.1]])

In [451]:
sm(L(M([1,1,2],[1,-1,2]), M([2],[1])))

array([[0.9],
       [0.1]])

In [452]:
sm(L(M([1,1,3],[1,-1,3]), M([2],[1])))

array([[0.9],
       [0.1]])

In [453]:
sm(L(M([1,1,3],[1,-1,5]), M([2],[1])))

array([[0.5],
       [0.5]])

In [454]:
sm(L(M([1,1,2],[1,-1,4]), M([2],[1])))

array([[0.5],
       [0.5]])

In [455]:
sm(L(M([1,1,0],[1,-1,2]), M([2],[1])))

array([[0.5],
       [0.5]])

In [456]:
sm(L(M([1,1,0],[1,-1,1]), M([2],[1])))

array([[0.75],
       [0.25]])

In [460]:
sm(L(M([1,1,-1],[1,-1,-1],[1,0,-2],[0,1,1]), M([2],[1])))

array([[0.45],
       [0.05],
       [0.05],
       [0.45]])

In [461]:
sm(L(M([1,1,-1],[1,-1,3],[1,0,0],[0,1,-1]), M([2],[1])))

array([[0.09],
       [0.81],
       [0.09],
       [0.01]])

In [462]:
sm(L(M([1,1,-3],[1,-1,0],[1,0,0],[0,1,2],[1,2,-4],[2,1,-3]), M([2],[1])))

array([[0.02],
       [0.06],
       [0.18],
       [0.54],
       [0.02],
       [0.18]])

In [485]:
M([0,1,2],[3,4,5])

array([[0, 1, 2],
       [3, 4, 5]])