In [1]:
import numpy as np
import pandas as pd
import logging

logger = logging.getLogger('matrices')
logger.setLevel(logging.DEBUG)
file_log = logging.FileHandler('matrix_transforms.log')
file_log.setLevel(logging.DEBUG)
console_log = logging.StreamHandler()
console_log.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_log.setFormatter(formatter)
console_log.setFormatter(formatter)
logger.addHandler(file_log)
logger.addHandler(console_log)

logger.info('initialized')
logger.debug('debug message')
logger.info('info message')
logger.warning('warn message')
logger.error('error message')
logger.critical('critical message')

2024-11-13 17:17:23,138 - matrices - INFO - initialized
2024-11-13 17:17:23,139 - matrices - DEBUG - debug message
2024-11-13 17:17:23,139 - matrices - INFO - info message
2024-11-13 17:17:23,139 - matrices - WARNING - warn message
2024-11-13 17:17:23,140 - matrices - ERROR - error message
2024-11-13 17:17:23,140 - matrices - CRITICAL - critical message


In [163]:
logger.info('defining functions')

def red(string):
    # return f'\x1b[31m{string}\x1b[0m' # disabled for logging
    return string

def blue(string):
    # return f'\x1b[34m{string}\x1b[0m'
    return string

def green(string):
    # return f'\x1b[32m{string}\x1b[0m'
    return string

def white(string):
    # return f'\x1b[107m{string}\x1b[0m'
    return string

def ppa(array):
    '''Pretty print array.'''
    logger.info(f'Value: {array}')
    logger.info(f'Shape: {array.shape[0]} x {array.shape[1]}')
    logger.info(f'Magnitude: {np.linalg.norm(array)}')

def ghc(vector3, w):
    '''Generate Homogenous Coordinates.
    
    `position` returns a position vector.
    `direction` returns a direction vector.'''

    match w:
        case 0:
            logger.info('Returning a homogenous direction.')
            return np.append(vector3, 0)
        case 1:
            logger.info('Returning a homogenous position.')
            return np.append(vector3, 1)
        case _:
            e = ValueError('Neither a position nor direction.')
            logger.error(e)
            raise e

def gtm(vector3):
    '''Get Translation Matrix given vector3'''

    # Flatten by removing axes of length one.
    flat_vector_3 = vector3.squeeze()
    
    # Separate the vector components
    x = flat_vector_3[0]
    y = flat_vector_3[1]
    z = flat_vector_3[2]
    
    # Create the transformation matrix
    matrix = np.array([
        [1,0,0,x],
        [0,1,0,y],
        [0,0,1,z],
        [0,0,0,1]
    ])

    logger.info(f'{red("Creating a")} {green("transformation matrix")}:\n\n{blue("from")}:\n{vector3}\n\n{blue("to")}:\n{matrix}\n')

    return matrix

def gsm(vector3):
    '''Get Scaling Matrix given vector3'''

    # Flatten by removing axes of length one.
    flat_vector_3 = vector3.squeeze()

    # Separate the vector components
    x = flat_vector_3[0]
    y = flat_vector_3[1]
    z = flat_vector_3[2]

    # Create the transformation matrix
    matrix = np.array([
        [x,0,0,0],
        [0,y,0,0],
        [0,0,z,0],
        [0,0,0,1]
    ])

    logger.info(f'{red("Creating a")} {green("scaling matrix")}:\n\n{blue("from")}:\n{vector3}\n\n{blue("to")}:\n{matrix}\n')

    return matrix

def origin(basis = [0,0,0]):
    logger.info(f'Generating origin at basis: {basis}.')
    return np.array([[0,0,0]])

def matrix_vector_dot(matrix, vector):
    '''Scale a vector3 position pos using a scaling matrix A'''
    ans = []

    # matrix-vector product
    for m_row in matrix:
        for index, component in enumerate(m_row):
            res = component * vector[index]
            logger.debug(f'{component} * {vector[index]} = {res}')
            if res != 0:
                ans.append(res)
    logger.info(f'{red("Creating a")} {green("scaled vector")}:\n\n{blue("from")}:\n{vector}\n\n{blue("and")}:\n{matrix}\n')
    
    if len(ans) == 1:
        return np.append(np.array([0,0,0]), (ans))

    return ans

# creates a matrix
# ans = []
# for m_row in matrix:
#     row = []
#     for index, component in enumerate(m_row):
#         row.append(component * vector[index])
#         print(f'{component} * {vector[index]} = {component * vector[index]}')
#         if index == 3:
#             print('new row')
#             ans.extend([row])
#             row = []

2024-11-13 19:09:10,445 - matrices - INFO - defining functions


In [164]:
# we create a user at (0,0,0)
# scale the user by 3, then
# move the user (3,2,1) units away.

# create user at origin and homogenize
user_position = origin()
user_world_position = ghc(user_position, 1)

# create scaling matrix
SCALAR = 3
DIMS = 3
scaling_vector = np.array(SCALAR).repeat(DIMS)
scaling_matrix = gsm(scaling_vector)

# update the user
user_world_position = matrix_vector_dot(scaling_matrix, user_world_position)
logger.info(f'user now at: {user_world_position}\n')

# create translation matrix
translation_vector = np.array([3,2,1])
translation_matrix = gtm(translation_vector)

user_world_position = matrix_vector_dot(translation_matrix, user_world_position)
logger.info(f'user now at: {user_world_position}\n')

2024-11-13 19:09:10,816 - matrices - INFO - Generating origin at basis: [0, 0, 0].
2024-11-13 19:09:10,818 - matrices - INFO - Returning a homogenous position.
2024-11-13 19:09:10,819 - matrices - INFO - Creating a scaling matrix:

from:
[3 3 3]

to:
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 1]]

2024-11-13 19:09:10,820 - matrices - DEBUG - 3 * 0 = 0
2024-11-13 19:09:10,820 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,821 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,821 - matrices - DEBUG - 0 * 1 = 0
2024-11-13 19:09:10,821 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,821 - matrices - DEBUG - 3 * 0 = 0
2024-11-13 19:09:10,822 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,822 - matrices - DEBUG - 0 * 1 = 0
2024-11-13 19:09:10,822 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,822 - matrices - DEBUG - 0 * 0 = 0
2024-11-13 19:09:10,823 - matrices - DEBUG - 3 * 0 = 0
2024-11-13 19:09:10,823 - matrices - DEBUG - 0 * 1 = 0
2024-11-13 19:09:10,823 - matrices - DEBUG 